#!/usr/bin/env python

import sys

import eventlet
eventlet.monkey_patch()

from nova import flags
from nova import log as logging
from nova import service
from nova import utils

if __name__ == '__main__':
    utils.default_flagfile()
    flags.FLAGS(sys.argv)
    logging.setup()
    utils.monkey_patch()
    server = service.Service.create(binary='metering-test',
                                    periodic_interval=60,
                                    topic='metering',
                                    manager='testmanager.MeteringManager',
                                    )
    service.serve(server)
    service.wait()
